In [1]:
###### importing dependencies ############################################
from cryptoaml import utils as util  

###### constants #########################################################
top_N = 10
experiment_1 = "persistence/experiment_1.1/tuning_studies/"

In [5]:
# # LightGBM 
# print("LightGBM - Random Search: 'Learning Rate' & 'No. of estimators'")
# lighgbm_rs = util.read_pickle(experiment_1 + "rs_lightgbm_ALL.pkl").trials_dataframe()
# display(lighgbm_rs.sort_values("value", ascending=False).head(top_N))

print("LightGBM - TPE")
lighgbm_tpe = util.read_pickle(experiment_1 + "tpe_lightgbm_ALL.pkl").trials_dataframe()
display(lighgbm_tpe.sort_values("value", ascending=False).head(top_N))

LightGBM - TPE

,number,value,datetime_start,datetime_complete,params_colsample_bytree,params_learning_rate,params_min_child_samples,params_min_child_weight,params_num_leaves,params_reg_alpha,params_reg_lambda,params_subsample,user_attrs_best_n_estimators,user_attrs_cv_max,user_attrs_cv_min,user_attrs_cv_std,state
0,0,0.980616,2020-05-01 00:53:49.960356,2020-05-01 00:54:38.838763,0.907345,0.144847,215,0.211632,548,0.000004,0.195695,0.994818,4179,0.988543,0.966997,0.007632,COMPLETE
1,1,0.976009,2020-05-01 00:54:38.839802,2020-05-01 00:55:35.674290,0.585820,0.002285,182,0.335768,363,0.000111,0.000009,0.746762,4759,0.980328,0.968699,0.005268,COMPLETE

In [3]:
# CatBoost 
print("CatBoost - Random Search: 'Learning Rate' & 'No. of estimators'")
catboost_rs = util.read_pickle(experiment_1 + "rs_catboost_ALL.pkl").trials_dataframe()
display(catboost_rs.sort_values("value", ascending=False).head(top_N))

CatBoost - Random Search: 'Learning Rate' & 'No. of estimators'

,number,value,datetime_start,datetime_complete,params_learning_rate,user_attrs_best_n_estimators,user_attrs_cv_max,user_attrs_cv_min,user_attrs_cv_std,state
4,4,0.985513,2020-04-30 18:53:39.160136,2020-04-30 18:54:36.584178,0.072112,190,0.993464,0.975288,0.006300,COMPLETE
25,25,0.985211,2020-04-30 19:14:18.765044,2020-04-30 19:15:16.197883,0.197779,3416,0.993464,0.976974,0.006077,COMPLETE
26,26,0.985203,2020-04-30 19:15:16.199767,2020-04-30 19:16:13.495308,0.078513,227,0.993464,0.976974,0.006336,COMPLETE
42,42,0.985197,2020-04-30 19:31:10.254855,2020-04-30 19:32:07.598912,0.078241,3090,0.991817,0.978654,0.005611,COMPLETE
8,8,0.984843,2020-04-30 18:57:29.111456,2020-04-30 18:58:25.985204,0.081598,139,0.993421,0.973597,0.007657,COMPLETE
38,38,0.984829,2020-04-30 19:27:07.889017,2020-04-30 19:28:05.915908,0.019507,4227,0.993443,0.975207,0.007140,COMPLETE
21,21,0.984513,2020-04-30 19:10:22.693165,2020-04-30 19:11:24.698678,0.004576,3017,0.991843,0.975207,0.006518,COMPLETE
17,17,0.984511,2020-04-30 19:06:21.278875,2020-04-30 19:07:23.812859,0.003439,4463,0.993443,0.973597,0.007362,COMPLETE
46,46,0.984214,2020-04-30 19:35:15.220571,2020-04-30 19:36:13.189797,0.089999,316,0.991763,0.976898,0.005621,COMPLETE
13,13,0.984203,2020-04-30 19:02:24.842377,2020-04-30 19:03:22.351598,0.086235,2888,0.991843,0.978512,0.005308,COMPLETE