In [1]:
###### importing dependencies ############################################
from cryptoaml import utils as util  

###### constants #########################################################
top_N = 10
experiment_1 = "persistence/experiment_1.1/tuning_studies/"

In [2]:
# LightGBM 
print("LightGBM - Random Search: 'Learning Rate' & 'No. of estimators'")
lighgbm_rs = util.read_pickle(experiment_1 + "rs_lightgbm_ALL.pkl").trials_dataframe()
display(lighgbm_rs.sort_values("value", ascending=False).head(top_N))

print("LightGBM - TPE")
lighgbm_tpe = util.read_pickle(experiment_1 + "tpe_lightgbm_ALL.pkl").trials_dataframe()
display(lighgbm_tpe.sort_values("value", ascending=False).head(top_N))

LightGBM - Random Search: 'Learning Rate' & 'No. of estimators'

,number,value,datetime_start,datetime_complete,params_learning_rate,user_attrs_best_n_estimators,user_attrs_cv_max,user_attrs_cv_min,user_attrs_cv_std,state
6,6,0.986854,2020-04-29 21:25:28.725901,2020-04-29 21:26:26.074923,0.034612,1290,0.990196,0.978654,0.004541,COMPLETE
15,15,0.985863,2020-04-29 21:34:54.571043,2020-04-29 21:35:46.747327,0.077107,4612,0.990196,0.981697,0.003121,COMPLETE
30,30,0.985858,2020-04-29 21:51:09.560517,2020-04-29 21:51:59.647694,0.160445,215,0.988543,0.983498,0.001693,COMPLETE
4,4,0.985566,2020-04-29 21:23:27.658560,2020-04-29 21:24:28.560264,0.024702,4591,0.990164,0.978793,0.004020,COMPLETE
7,7,0.985537,2020-04-29 21:26:26.076867,2020-04-29 21:27:58.450379,0.005892,3307,0.991817,0.978583,0.004235,COMPLETE
38,38,0.985238,2020-04-29 21:58:40.317254,2020-04-29 21:59:30.573901,0.146737,153,0.990132,0.980263,0.003722,COMPLETE
29,29,0.985222,2020-04-29 21:49:55.597754,2020-04-29 21:51:09.557571,0.010164,3247,0.993443,0.980132,0.004439,COMPLETE
39,39,0.985217,2020-04-29 21:59:30.579253,2020-04-29 22:00:24.452943,0.055485,3081,0.991817,0.981878,0.003755,COMPLETE
36,36,0.985206,2020-04-29 21:56:26.591563,2020-04-29 21:57:46.266771,0.007990,2288,0.990164,0.977049,0.004857,COMPLETE
3,3,0.984882,2020-04-29 21:22:31.581064,2020-04-29 21:23:27.657179,0.058241,213,0.991817,0.978512,0.004935,COMPLETE

LightGBM - TPE

,number,value,datetime_start,datetime_complete,params_colsample_bytree,params_min_child_samples,params_min_child_weight,params_num_leaves,params_reg_alpha,params_reg_lambda,params_subsample,user_attrs_cv_max,user_attrs_cv_mean,user_attrs_cv_min,user_attrs_cv_std,system_attrs_fail_reason,state
43,43,0.987520,2020-04-30 00:32:35.606965,2020-04-30 00:32:42.816420,0.650840,28,1.392469e-05,625,2.868878e-05,0.013137,0.682702,0.996721,0.987520,0.978723,0.007809,NaN,COMPLETE
25,25,0.985876,2020-04-30 00:31:03.746220,2020-04-30 00:31:12.815802,0.743071,31,1.624032e-06,22,7.597295e-06,0.000057,0.696534,0.991843,0.985876,0.980328,0.003996,NaN,COMPLETE
46,46,0.985852,2020-04-30 00:32:55.808900,2020-04-30 00:33:02.564765,0.592490,17,1.343395e-07,694,2.645004e-04,0.266549,0.645788,0.995074,0.985852,0.976974,0.006981,NaN,COMPLETE
44,44,0.984899,2020-04-30 00:32:42.822502,2020-04-30 00:32:50.357454,0.645315,25,1.526048e-07,599,5.199300e-05,0.010190,0.706648,0.993443,0.984899,0.978793,0.004899,NaN,COMPLETE
13,13,0.984883,2020-04-30 00:30:05.525736,2020-04-30 00:30:11.235572,0.593897,41,1.504296e-03,249,1.660594e-07,0.032156,0.589814,0.988543,0.984883,0.981878,0.002210,NaN,COMPLETE
11,11,0.984854,2020-04-30 00:29:54.635345,2020-04-30 00:30:00.216968,0.657713,10,2.780498e-02,153,1.182121e-07,0.000002,0.514546,0.991790,0.984854,0.975124,0.005909,NaN,COMPLETE
32,32,0.984606,2020-04-30 00:31:41.897049,2020-04-30 00:31:51.736547,0.738263,28,1.879016e-06,76,1.401623e-05,0.007605,0.768570,0.991790,0.984606,0.972358,0.006666,NaN,COMPLETE
6,6,0.984551,2020-04-30 00:29:31.480747,2020-04-30 00:29:38.399165,0.660082,33,2.239575e-05,871,2.813912e-05,0.015580,0.673865,0.988468,0.984551,0.980263,0.002887,NaN,COMPLETE
33,33,0.984539,2020-04-30 00:31:51.742685,2020-04-30 00:31:59.613909,0.747953,87,1.150528e-06,73,3.899476e-04,0.004052,0.815521,0.986842,0.984539,0.980328,0.002430,NaN,COMPLETE
36,36,0.984532,2020-04-30 00:32:08.349366,2020-04-30 00:32:14.759697,0.767067,66,9.919462e-04,231,1.454944e-06,0.044397,0.760187,0.990196,0.984532,0.980198,0.003273,NaN,COMPLETE

In [4]:
# CatBoost 
print("CatBoost - Random Search: 'Learning Rate' & 'No. of estimators'")
catboost_rs = util.read_pickle(experiment_1 + "rs_catboost_ALL.pkl").trials_dataframe()
display(catboost_rs.sort_values("value", ascending=False).head(top_N))

display(catboost_rs.sort_values("value", ascending=False).head(1).values)

CatBoost - Random Search: 'Learning Rate' & 'No. of estimators'

,number,value,datetime_start,datetime_complete,params_learning_rate,user_attrs_best_n_estimators,user_attrs_cv_max,user_attrs_cv_min,user_attrs_cv_std,state
43,43,0.986530,2020-04-30 06:31:22.358181,2020-04-30 06:34:12.816760,0.008664,2807,0.990164,0.978654,0.004322,COMPLETE
25,25,0.986511,2020-04-30 05:41:09.066548,2020-04-30 05:43:55.462187,0.074837,300,0.991790,0.980198,0.004263,COMPLETE
0,0,0.986500,2020-04-30 04:31:19.890020,2020-04-30 04:34:06.525274,0.022473,1494,0.991736,0.980000,0.004139,COMPLETE
18,18,0.986180,2020-04-30 05:21:37.342962,2020-04-30 05:24:24.900659,0.021436,2729,0.993464,0.976821,0.005431,COMPLETE
22,22,0.986178,2020-04-30 05:32:47.417692,2020-04-30 05:35:36.911417,0.010444,1241,0.990196,0.981878,0.002696,COMPLETE
42,42,0.985893,2020-04-30 06:28:32.765459,2020-04-30 06:31:22.354905,0.075177,245,0.988581,0.981878,0.002683,COMPLETE
29,29,0.985888,2020-04-30 05:52:18.696562,2020-04-30 05:55:04.321581,0.181595,634,0.990196,0.976974,0.004853,COMPLETE
1,1,0.985872,2020-04-30 04:34:06.525901,2020-04-30 04:36:58.087581,0.126740,147,0.993443,0.980328,0.004701,COMPLETE
16,16,0.985869,2020-04-30 05:16:02.869592,2020-04-30 05:18:50.445251,0.053704,541,0.990099,0.981938,0.003013,COMPLETE
21,21,0.985855,2020-04-30 05:29:59.911198,2020-04-30 05:32:47.415954,0.030316,442,0.988506,0.981997,0.002429,COMPLETE

array([[43, 0.98652976898, Timestamp('2020-04-30 06:31:22.358181'),
        Timestamp('2020-04-30 06:34:12.816760'), 0.00866434394567924,
        2807, 0.9901639344, 0.9786535304, 0.004322317831931517,
        'COMPLETE']], dtype=object)